config/routes.rb
Rails.application.routes.draw do

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    post 'user/login'
    get 'user/new'
    post 'user/logout'
    get 'user/admin_login'
    post 'user/admin_password_validation'
    
    post 'events/new'
    get 'events/sign_up_for_event'
    post 'events/sign_up_for_event'
    post 'events/remove_from_event'
    
    get 'attendances/event_attendees'
    post 'attendances/event_attendees'
    post 'attendances/remove_from_event'
    
    get 'points/meeting'
    post 'points/meeting_signin'
    # get 'points/view_approve_event'
    # post 'points/select_approve_event'
    get 'points/select_approve_points'
    post 'points/view_users_approval'
    get 'points/view_users_approval'
    post '/points/approve_points'
    get 'points/user_list'
    get 'points/member_activity_table'
    post 'points/update'
    get 'points/user_csv'
    
    #   get 'events/new'
    
    get 'dashboard/index'
    post 'dashboard/index'
    
    get 'attendances/view_details'
    post 'attendances/view_details'
    
    post 'img_upload/create'
    
    post 'admin/update'
    get 'admin/export_data'
    
    resources :events
    resources :user
    resources :points
    resources :attendances
    resources :admin
    
    root 'user#login'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def index
    if !session[:admin]
      
      @user = User.find_by(:UIN => session[:user_uin])
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_admin_dashboard.html.erb
<!-- redirects members trying to "hack" into the admin pages -->
<%= member_redirect() %>

<center><h1>Welcome Admin!</h1></center>
<!--<button id="create-event-btn" class="btn btn-default btn-lg">Create Event</button>-->
<%= render 'layouts/flash_messages' %>
<div class="button-pad page-margins">
    <center>
        <a href=<%= new_event_path %> class="btn btn-default btn-lg" id="create-event-btn">Create Event</a>
        <a href=<%= points_meeting_path %> class="btn btn-default btn-lg" id="meeting-login-btn">Meeting Login</a> 
        <a href=<%= user_index_path %> class="btn btn-default btn-lg" id="edit-user-btn">Edit Members</a> 
        <a href=<%= points_user_list_path %> class="btn btn-default btn-lg" id="member-activity-btn">View Members Points</a>
        <a href=<%= edit_admin_path(1) %> class="btn btn-default btn-lg" id="edit-admin-btn">Change Password</a> 
    </center>
    <br><br>
    <center>
        <%= cl_image_tag("Aggie-Rotaract-Homepage.jpeg", height: '500', width: '800') %>
    </center>
</div>

app/views/dashboard/_member_dashboard.html.erb
<script type="text/javascript">
    window.location.href="/attendances"  // put your correct path in a string here
</script>

app/views/dashboard/index.html.erb
<!-- Dashboard/index -->
<%= render :partial => "admin_dashboard" if session[:admin] %>
<%= render :partial => "member_dashboard" if !session[:admin] %>