config/routes.rb
Rails.application.routes.draw do

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    post 'user/login'
    get 'user/new'
    post 'user/logout'
    get 'user/admin_login'
    post 'user/admin_password_validation'
    
    post 'events/new'
    get 'events/sign_up_for_event'
    post 'events/sign_up_for_event'
    post 'events/remove_from_event'
    
    get 'attendances/event_attendees'
    post 'attendances/event_attendees'
    post 'attendances/remove_from_event'
    
    get 'points/meeting'
    post 'points/meeting_signin'
    # get 'points/view_approve_event'
    # post 'points/select_approve_event'
    get 'points/select_approve_points'
    post 'points/view_users_approval'
    get 'points/view_users_approval'
    post '/points/approve_points'
    get 'points/user_list'
    get 'points/member_activity_table'
    post 'points/update'
    get 'points/user_csv'
    
    #   get 'events/new'
    
    get 'dashboard/index'
    post 'dashboard/index'
    
    get 'attendances/view_details'
    post 'attendances/view_details'
    
    post 'img_upload/create'
    
    post 'admin/update'
    get 'admin/export_data'
    
    resources :events
    resources :user
    resources :points
    resources :attendances
    resources :admin
    
    root 'user#login'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/point.rb
require 'csv'
class Point < ApplicationRecord
    def self.to_csv
        CSV.generate(headers: true) do |csv|
            csv << %w{ event member points issue_date } 
            all.each do |rec|
                # Event Name
                event_name = Event.find(rec.event_id).name
                # User Name
                member = User.find_by(:UIN => rec.UIN).name
                
                csv << [ event_name, member, rec.points, rec.issue_date.strftime("%B %d, %Y")]
            end
        end
    end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
    before_filter :authenticate_user!
    include PointsHelper
    
    UserPoints = Struct.new(:active_record, :event)
    
    def index
        @events = Array.new
        
        if (!session[:user_uin].nil?)
            #session user uin
            @users_points = Point.where(UIN: session[:user_uin])
            @userName = User.find_by(UIN: session[:user_uin]).name
            
    
            @users_points.each do |user_pt|
                event = Event.find(user_pt.event_id)
                @events.append(UserPoints.new(user_pt, event))
            end
            
            #sort @events by the date
            @events.sort! { |a, b| a.event.date <=> b.event.date}
    
    
            if !params[:view_event].nil?
                @view_event = Event.find(params[:view_event])
                event_contact = User.find_by(UIN: @view_event.contact)
                @view_event.contact = event_contact.email 
            end
        end
        @all_points = Point.all
        respond_to do |format|
              format.html
              format.csv { send_data @all_points.to_csv, filename: "points-#{Date.today}.csv" }
              format.pdf do
                  pdf = UserPointsPdf.new(@events, session[:user_uin])
                  send_data pdf.render, filename: "user-points-#{Date.today}.pdf"
              end
        end
        
    end
    
    def create
        @user_uin = params[:user_uin]
        @user_points = params[:points]
        
        # loops through both arrays pairing the values by index
        # or if looking at the table on website then it is by row matching the uin and the points
        @user_uin.zip(@user_points).each do |uin, points|
            curr_time = DateTime.now.to_date
            
            # if admin resubmits the form we need to overwrite the data in there not append
            if Point.exists?(:event_id => params[:event_id],:UIN => uin)
                Point.find_by(:event_id => params[:event_id],:UIN => uin).destroy
            end
            
            @point = Point.create!(:event_id => params[:event_id],
                                    :UIN => uin,
                                    :points => points,
                                    :issue_date => curr_time)
            
            @point.save
                
            # set the approved variable to true in Attendance model
            @attendance_record = Attendance.find_by(UIN: uin, event_id: params[:event_id])
            @attendance_record.update_attribute(:approved, true)
            @attendance_record.save
            
                        
            # check if user reached 30 points
            is_active = is_user_active(uin)
            if is_active
                user = User.find_by(:UIN => uin)
                user.update_attribute(:active, true)
                user.save
                puts "--- user earned 30 points is now ACTIVE"
            else
                puts "--- user is NOT ACTIVE"
            end
        end
     
        flash[:success] = "Points were successfully distributed"
    
        redirect_to points_view_users_approval_path(:event => params[:event_id])
    end
    
    
    def meeting
        curr_time = DateTime.now.to_date
        all_events = Event.all
        # populate dropdown list
        @upcoming_meetings = all_events.where("date >= :date and meeting = :meeting", {date: curr_time, meeting: [true]})
        puts "-----------meetings: " + @upcoming_meetings.to_s
    end
    
    def meeting_signin
        if params[:meeting_id].nil?
            flash[:danger] = "Sorry, you did not select a meeting!"
            redirect_to points_meeting_path
        else
            #grab uin
            uin = params[:uin]
            
            #check to see if UIN exists
            if User.exists?({:UIN => uin})
                name = User.find_by({:UIN => uin}).name
                # check if that user already signed in for this meeting
                if(Point.exists?({:UIN => uin, :event_id => params[:meeting_id]}))
                   # display error/warning message that user already signed in for that meeting
                   meeting_name = Event.find(params[:meeting_id]).name
                   flash[:warning] = name + " has already signed in for " + meeting_name
                   redirect_to points_meeting_path(:event_id => meeting)
                else
                    # add user to meeting
                    
                    meeting = Event.find(params[:meeting_id])
                    points = meeting.max_points
                    issue_date = DateTime.now.to_date
                    
                    point = Point.create!(:event_id => params[:meeting_id],
                                          :points => points,
                                          :UIN => params[:uin],
                                          :issue_date => issue_date)
                                          
                    point.save
                    flash[:success] = name + " has successfully signed in"
                    
                    # check if user reached 30 points
                    is_active = is_user_active(uin)
                    if is_active
                        user = User.find_by(:UIN => uin)
                        user.update_attribute(:active, true)
                        user.save
                        puts "--- user earned 30 points is now ACTIVE"
                    else
                        puts "--- user is NOT ACTIVE"
                    end
                    
                    
                    redirect_to points_meeting_path(:event_id => meeting, :event_name => meeting.name)
                end
            else
                #if not, offer to create new user
                flash[:warning] = "Invalid UIN. Do you need to Sign Up?"
                redirect_to points_meeting_path(:event_id => meeting)
            end
            
        end      
    end
    
    def show
    end
    
    def select_approve_points
        curr_time = DateTime.now.to_date
        # places the most recent events at the top of the list
        db_events = Event.order(date: :desc).all
        @past_events = db_events.where("date <= :date and meeting = :meeting", {date: curr_time, meeting: [false]})
        
        puts "---- past_events -> " + @past_events.to_s
        @past_events.each do |event|
            puts "--- event: " + @past_events.name 
        end
    end
    
    UserAttendance = Struct.new(:active_record, :name, :points)
    
    def view_users_approval
        @user_attendance = Attendance.where("event_id = :event_id and wait_listed = :wait_listed", {event_id: params[:event], wait_listed: [false]})
        @event = Event.find(params[:event])
        
        @users = Array.new
        
        @user_attendance.each do |user_att|
            uin = user_att.UIN
            user = User.find_by(UIN: uin)
            points_record = Point.find_by(event_id: params[:event], UIN: uin)
            
            if points_record.nil?
                @users.append(UserAttendance.new(user_att, user.name, 0))
            else
                @users.append(UserAttendance.new(user_att, user.name, points_record.points))
            end 
        end
    end
    
    
    def user_list
        @users = User.order(:name).all
    end
    
    #Struct for displaying the Member Activity Table
    MemberActivity = Struct.new(:event,:points)
    
    #Controller for the Member Activity Table
    def member_activity_table
        
        #Reads in the selected user
        user_id = params[:format]
        @user = User.find(user_id)
        # users_points = Point.where("UIN = :UIN",{UIN: @user.UIN})
        users_points = Point.where(:UIN => @user.UIN)
        
        #Gather the data to be displayed in the table
        @users_event_points = []
        users_points.each do |point_object|
            @users_event_points.append(MemberActivity.new(Event.find(point_object.event_id),point_object))
        end
    end
    
    #Updates a points object
    def update
        params[:points].each do |point_id|
            cur_point  = Point.find(point_id)
            input_points = params[:points][point_id][:points]
            
            if cur_point.points.to_s != input_points
                cur_point.update_attributes!(:points => input_points,
                                                :updated_at => DateTime.now)
            end
        end
        redirect_to :back
        flash[:success] = "Points were successfully updated."
    end
    
    def edit_all
        @users = Point.all
    end
    
#     def user_csv
        
#         user_points = Point.where(:UIN => session[:user_uin])
        
#         respond_to do |format|
#               format.html
#               format.csv { send_data user_points.user_points_csv, filename: "user-point-#{Date.today}.csv" }
#          end
# 	end
end

app/helpers/points_helper.rb
module PointsHelper
    
    def is_user_active uin
        puts "-- uin " + uin.to_s
        @records = Point.where(:UIN => uin)
        total = 0
        @records.each do |rec|
            total = total + rec.points
        end
        
        puts "--- points: " + total.to_s
        
        if total >= 30
            puts "--- user is active! "
            return true
        else
            puts "--- user is NOT active! "
            return false
        end
        
    end
    
end

app/views/points/index.html.erb
<h1 class="title">My Points</h1>
<% total=0%>
<% @events.each do |event| %>
    <% total=event[:active_record].points+total%>
<% end %>
<div class="row">
    <h3 class="col-sm-8" style="margin-left: 6em;"> Total Points: <%= total %></h3>
    <!-- <div class="col-sm-2">
        < if !params[:view_event].nil? %>
            <a href=<%= points_path(:view_event => params[:view_event], format: "pdf") %> class="btn btn-success btn-lg" id="export-user-points-csv">Export Data</a>
        < else %>
            <a href=<%= points_path(format: "pdf") %> class="btn btn-primary" id="export-user-points-csv">Export Data</a>
        < end %>
    </div> -->
</div>
<div class="">
    <% if is_user_active session[:user_uin] %>
        <h2><div class="label label-success center-label">Congrats You are an Active Member</div></h2>
    <% end %>
</div>
<br/>
<div class="page-margins">
	<div class="table-responsive">
	  <table class="table table-striped">
		  <tr>
		    <th class="col-sm-1">Event/Meeting</th>
		    <th class="col-sm-1">Date</th> 
		    <th class="col-sm-1">Points</th>
		    <th class="col-sm-1"></th>
		  </tr>
			<% @events.each do |event| %>
				<tr>
				    <td> <%= event[:event].name %> </td>
				    <td> <%= event[:event].date.strftime("%B %d, %Y")%> </td>
				    <td> <%= event[:active_record].points %> </td>
				    <td>
				    	<%= link_to  "View Event", points_path(:view_event => event[:event].id), class: "btn btn-default" %>
				    </td>
				  </tr>
			<% end %>
		</table>
	</div>
</div>

<br/><br/>

<% if @view_event.present? %>

<div class="event-card">
        <div class="row">
            <div class="col-sm-9">
                <div class="row col-sm-12">
                    <h3 id="event_title"><%= @view_event.name %></h3>
                </div>
                <div class="row col-sm-12">
                    <b>Time: </b>
                    <div class="event-item-margin">
                        <%= @view_event.start_time.strftime("%I:%M %p")%>
                        -
                        <%= @view_event.end_time.strftime("%I:%M %p") %>
                    </div>
                </div>
                <div class="row col-sm-12">
                    <b>Date: </b>
                    <div class="event-item-margin">
                        <%= @view_event.date.strftime("%B %d, %Y") %>
                    </div>
                </div>
                <div class="row col-sm-12">
                    <b>Contact: </b>
                    <div class="event-item-margin">
                        <%= @view_event.contact %>
                    </div>
                </div>
                <b>Description: </b>
                <div class="row col-sm-12">
                    <%= @view_event.description %>
                </div>
            </div>
            
            <div class="col-sm-3">
                <div class="row col-sm-12">
                    Points: 
                    <%= @view_event.max_points %>
                </div>
                <div class="row col-sm-12 event-image">
                    <!-- images are stored on cloudinary -->
                    <%= cl_image_tag(@view_event.image, class: "img-thumbnail") %>
                </div>
                <div class="row col-sm-12">
                    <a href="" id="address" class="address" target="_blank"><%= @view_event.address %></a>
                </div>
            </div>
        </div>
    </div>
<% end %>

<script>
// couldnt get the script to run from any of the coffee files 
$(document).ready(function(){
    var $editItem, $elements, $link, $pluslink, i;
    $elements = document.getElementsByClassName('address');
    i = 0;
    while (i < $elements.length) {
        $editItem = $elements[i];
        $link = $editItem.text;
        $pluslink = $link.replace(/\s+/g, '+');
        $elements[i].href = 'https://www.google.com/maps?q=' + $pluslink;
        $elements[i].text = 'Google Maps Link';
        i++;
    }
});
</script>

app/views/points/meeting.html.erb
<!-- redirects members trying to "hack" into the admin pages -->
<%= member_redirect() %>



<h1 class="title">Meeting Sign In</h1>
<%= render 'layouts/flash_messages' %>
<br>
<div class="meeting-form">
    <%= form_tag :method => :post, :class => '', :controller => 'points', :url => points_meeting_signin_path, :action => 'meeting_signin' do %>
    
        <div class="row col-sm-12 form-group"> <!-- Dropdown list -->
            <select class="btn-group bootstrap-select show-tick" name="meeting_id" required>
                
                <% if params[:event_id].nil? %>
                    <option disabled selected value> -- Select Meeting -- </option>
                <% end %>
                
                <% @upcoming_meetings.each do |event| %>
                    <% if event.id == params[:event_id] %>

                        <!--<option value=<= event.id %> selected> <= event.name %> </option>-->

                        <option id="meeting-option" value=<%= event.id %> selected> <%= event.name %> </option>

                    <% else %>
                        <option id="meeting-option" value=<%= event.id %>> <%= event.name %> </option>
                    <% end %>
                <% end %>
            </select>
        </div>
        <div class="row col-sm-12 form-group"> <!-- UIN label -->
            UIN:
        </div>
        <div class="row col-sm-12 form-group"> <!-- UIN text box -->
            <input id="uin_input" class="form-control" type="text" name="uin"  placeholder="UIN" value="" required>
        </div>
        <div class="row col-sm-12 form-group"> <!-- Buttons -->
            <div class="col-md-6">
                <button name="login_button" id="login_button_id" class="btn btn-lg btn-primary btn-block" type="submit">Log In</button>
            </div>
            <div class="col-md-6">
                <a href=<%= new_user_path %> id="sign_up_button_id" class="btn btn-lg btn-default btn-block">Sign Up</a>
            </div>
        </div>
    
    <% end %>
</div>

app/views/points/member_activity_table.html.erb
<!-- redirects members trying to "hack" into the admin pages -->
<%= member_redirect() %>

<h1 class="title">Member Activity</h1>
<%= render 'layouts/flash_messages' %>
<div class="page-margins">
    <div class="row">
      <div class="col-md-3">
        <font size = 4>
          <strong>Member: </strong><%= @user.name %>
        </font>
      </div>
      <div class="col-md-9">
        <font size = 4>
          <strong>UIN: </strong><%= @user.UIN %>
        </font>
      </div>
    </div>
    <br>
      
  <% if @users_event_points.empty? %>
    <center>
      <font size="7">
        <%= @user.name + " has no points" %>
      </font>
      <hr style="height:10pt; visibility:hidden;" />
    </center>
  <% else %>
  	<div class="table-responsive">
  	  <table class="table table-striped">
  		  <tr>
  		    <th class="col-sm-4">Event/Meeting</th>
  		    <th class="col-sm-4">Date</th> 
  		    <th class="col-sm-4">Points</th>
  		  </tr>
        <%= form_tag points_update_path do %>
          <% @users_event_points.each do |user_event_point| %> 
            <%= fields_for "points[]", user_event_point[:points] do |pf| %>
              <tr>
                <td><%= user_event_point[:event].name %></td>
                <td><%= user_event_point[:event].date.strftime("%B %d, %Y") %></td>
                <td><%= pf.text_field :points, style: 'width:25%;', :required=> true,  type: "number", class: "form-control" %></td>
              </tr>
            <% end %>
          <% end %>
  		</table>
    	<div class="pull-right">
          <a href="<%= points_user_list_path %>" id="cancel_update_btn" class="btn btn-default">Back To List</a>
          <%= submit_tag "Update All Points", :class => "btn btn-success"%>
      </div>
    <% end %>
  <% end %>

app/views/points/select_approve_points.html.erb
<!-- redirects members trying to "hack" into the admin pages -->
<%= member_redirect() %>

<h1 class="text-center">Select Event to Approve Points</h1>
<br/>

<%= form_tag :method => :post, :class => 'form-signin', :controller => 'points', :action => 'view_users_approval' do %>
    
    <div class="row">
        <div class="row col-sm-offset-4">
            <!-- class = "selectpicker" is causing issues for heroku -->
            <select class="btn-group bootstrap-select show-tick" name="event" required>
                <% if params[:event_id].nil? %>
                    <option disabled selected value> -- Select Event -- </option>
                <% end %>
                <% @past_events.each do |event| %>
                    <% if event.id == params[:event_id] %>
                        <option value=<%= event.id %>selected> <%= event.name %> </option>
                    <% else %>
                        <option value=<%= event.id %>> <%= event.name %> </option>
                    <% end %>
                <% end %>
            </select>
        </div>

        <div class="row form-actions">
            <button class="btn btn-md btn-primary btn-block col-sm-offset-6" type="submit">Load Users</button>
        </div>
    </div>
    
<% end %>

app/views/points/user_list.html.erb
<style style="text/css">
.table-hover tbody tr:hover td, .table-hover tbody tr:hover th {
  background-color: #dedede;
}
</style>

<!-- redirects members trying to "hack" into the admin pages -->
<%= member_redirect() %>

<div class="container">

  <h2>Select Member</h2>
  <h4><span class="label label-primary">Please select a member's activity to view</span></h4>
  <%= render 'layouts/flash_messages' %>

  
  <div class="page-margins">
    <div class="table-responsive">
      <table class="table table-striped table-hover table-fixed">
        <thead>
          <tr>
            <th class="col-sm-1">Name</th>
            <th class="col-sm-1">UIN</th>
            <th class="col-sm-1">Officer</th>
            <th class="col-sm-1">Active</th>
            <th class="col-sm-1">Email</th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr data-link="<%= points_member_activity_table_path(user.id) %>">
              <td><%= user.name %></td>
              <td><%= user.UIN %></td>
              <td>
                <% if user.officer %>
                  <span class="glyphicon glyphicon-ok" style="color: green;"></span>
                <% end %>
              </td>
              <td>
                <% if user.active %>
                  <span class="glyphicon glyphicon-ok" style="color: green;"></span>
                <% end %>
              </td>
              <td><%= user.email %></td>
              <!--<td><= user.UIN %></td>-->
              <!--<td><= user.name %></td>-->
              <!--<td>x</td>-->
              <!--<td>Input Stuff here</td>-->
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  
  <% if flash[:success] %>
    <div class="alert <= "alert-success" %> fade in">
      <button class="close" data-dismiss="alert">×</button>
      Update Success
    </div>
  <% end %>
</div>

<script>
    $("tr[data-link]").click(function() {
  window.location = $(this).data("link")
})
</script>

<script>
  setTimeout("$('.alert').fadeOut('slow')", 1000)
</script>

app/views/points/view_users_approval.html.erb
<!-- redirects members trying to "hack" into the admin pages -->
<%= member_redirect() %>

<%= render 'layouts/flash_messages' %>
<% if !@users.nil? %>
    <h1 class="title">Approve Points for "<%= @event.name %>"</h1>
    <br/>
    
    <div class="page-margins">
        
        <%= form_tag :method => :post, :controller => 'points', :action => 'create', :event_id => @event.id do %>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th class="col-md-2">UIN</th>
                            <th class="col-md-2">Name</th>
                            <th class="col-md-2"><%= @event.name %></th>
                            <th class="col-md-3">Points</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @users.each do |user| %>
                            <tr>
                                <td>
                                    <%= user[:active_record].UIN %>
                                    <!-- below is the only way i could figure out how to pass the uins -->
                                    <input type="hidden" name="user_uin[]" value=<%= user[:active_record].UIN %> />
                                </td>
                                <td><%= user[:name] %></td>
                                <td><%= user[:points]%></td>
                                <td>
                                    <input name="points[]" id="points_id" class="col-sm-4" type="number" step="0.5" value=<%= @event.max_points %> required>
                                    </td>
                                <td>
                                    <%= link_to events_remove_from_event_path(:remove_me_location => "approve_points", :user_uin => user[:active_record].UIN, :event_id => @event.id),
                                        :method => :post, class: "btn btn-danger pull-right" do %>
                                            <span class='glyphicon glyphicon-remove' aria-hidden='true' style='color: white'></span>
                                    <% end %>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
            
            <div class="pull-right">
                <a href=<%= new_attendance_path(:event_id => @event.id) %> name="/attendances/new" id="add_attendance_button_id" class="btn btn-md btn-default">Add a Member</a>
                <button class="btn btn-md btn-success" type="submit">Submit Points</button>
            </div>
        <% end %>
    </div> <!-- .page-margins --> 
<% end %>