config/routes.rb
Rails.application.routes.draw do

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    post 'user/login'
    get 'user/new'
    post 'user/logout'
    get 'user/admin_login'
    post 'user/admin_password_validation'
    
    post 'events/new'
    get 'events/sign_up_for_event'
    post 'events/sign_up_for_event'
    post 'events/remove_from_event'
    
    get 'attendances/event_attendees'
    post 'attendances/event_attendees'
    post 'attendances/remove_from_event'
    
    get 'points/meeting'
    post 'points/meeting_signin'
    # get 'points/view_approve_event'
    # post 'points/select_approve_event'
    get 'points/select_approve_points'
    post 'points/view_users_approval'
    get 'points/view_users_approval'
    post '/points/approve_points'
    get 'points/user_list'
    get 'points/member_activity_table'
    post 'points/update'
    get 'points/user_csv'
    
    #   get 'events/new'
    
    get 'dashboard/index'
    post 'dashboard/index'
    
    get 'attendances/view_details'
    post 'attendances/view_details'
    
    post 'img_upload/create'
    
    post 'admin/update'
    get 'admin/export_data'
    
    resources :events
    resources :user
    resources :points
    resources :attendances
    resources :admin
    
    root 'user#login'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/event.rb
require 'csv'
class Event < ApplicationRecord
    def self.to_csv
        CSV.generate(headers: true) do |csv|
            csv << %w{ id name address date description start_time end_time capacity max_points meeting contact image } 
            all.each do |event|
                #date
    			date = event.date.strftime("%B %d, %Y") 
    			
    			#time
    			start_time = event.start_time.strftime("%I:%M %p")
            	end_time = event.end_time.strftime("%I:%M %p")
    			
    			#contact UIN to name
    			contact = User.find_by(UIN: event.contact).name 
                csv << [event.id, event.name, event.address, date, event.description, start_time, end_time, event.capacity, event.max_points, event.meeting, contact, event.image ]
            end
        end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_filter :authenticate_user!
    
    def index
        curr_time = DateTime.now.to_date
        @all_events = Event.order(:date).all
        
        if !session[:user_uin].nil?
            puts '--- member is logged in'
            @upcoming_events = @all_events.where("date >= :date and meeting = :meeting and publish = :published", {date: curr_time, meeting: [false], published: [true]})
        else
            puts '--- ADMIN is logged in'
            @upcoming_events = @all_events.where("date >= :date and meeting = :meeting", {date: curr_time, meeting: [false]})
        end
        
        @upcoming_events_email = @upcoming_events
        contact_uin_to_email
        
        respond_to do |format|
        	format.html            
        	format.csv { send_data Event.order(:date).all.to_csv, filename: "events-#{Date.today}.csv" }
        end
    end
    
    def new
        grab_officers
    end

    def remove_from_event
        
        if params[:remove_me_location] == "approve_points" # removing member from list from the approval points page
            # if the points are already in the database we need to remove that record as well essentially removing the points fomr that user
            if Point.exists?(:event_id => params[:event_id],:UIN => params[:user_uin])
                Point.find_by(:event_id => params[:event_id],:UIN =>  params[:user_uin]).destroy
            end
        else
            if Attendance.where(:UIN => session[:user_uin]).where(:event_id => params[:event_id]).where(:wait_listed => false).present?
                if Attendance.where(:event_id => params[:event_id]).where(:wait_listed => true).present?
                    @waitlist=Attendance.where(:event_id => params[:event_id]).where(:wait_listed => true)
                    @sorted_waitlist = @waitlist.sort { |a,b| a.time_stamp <=> b.time_stamp }
                    @sorted_waitlist[0].update_attribute :wait_listed, false
                end
            end
        end
        # find out is user is going
            # query grab Attendances.where event_id = id waitlist = true
            # doe the sort
            # make index 0 user waitlist boolean = false
        
        # admin removing member from the attendance list in the approve points page (/points/view_users_approval)
        uin = session[:user_uin]
        if !params[:user_uin].nil? 
            uin = params[:user_uin] 
        end
        
        Attendance.where(:UIN => uin).where(:event_id => params[:event_id]).destroy_all
        
        if !params[:user_uin].nil?
            flash[:success] = "The user was deleted from the event and we removed the points for them!"
            redirect_to points_view_users_approval_path(:event => params[:event_id])
        else
            flash[:success] = "You have been removed from the event!"
            redirect_to :back
        end
        
    end
    
    def destroy
        puts params[:id]
        Attendance.where(:event_id => params[:id]).destroy_all
        Event.find(params[:id]).destroy()
        redirect_to :back
        flash[:success] = "You successfully deleted " + params[:event_name] + "!"
    end
    
    def create
        
        #upload image to cloudinary for storage
        puts "--- image: " + params[:image]
        if !params[:image].empty?
            file_dir = "public/images/" + params[:image]
            Cloudinary::Uploader.upload(file_dir, :use_filename => true, :unique_filename => false)
        end
        
        # convert date input to correct format for database
        date = date_conversion
        
        puts "--- params publish " + params[:publish].to_s
        
        @event = Event.create!(:name => params[:name],
                 :description => params[:description],
                 :address => params[:address],
                 :meeting => params[:meeting],
                 :date => date,
                 :start_time => params[:start_time],
                 :end_time => params[:end_time],
                 :max_points => params[:max_points],
                 :capacity => params[:capacity],
                 :contact => params[:contact],
                 :publish => params[:publish],
                 :image => params[:image])
                 
        @event.save
        
        # make the officer an automatic person on the going list
        @attendance = Attendance.create!(:UIN => params[:contact],
    		:event_id => @event.id,
    		:car_ride => false,
    		:comments => "I am your point of contact for this event",
    		:pref_contact => "Email",
    		:wait_listed => false,
    		:approved => false
    		)
    	@attendance.save
        
        
        if !@event.name.nil?
            flash[:success] = "Successfully Created Event: " + @event.name
        end
        redirect_to dashboard_index_path 
    end
    
    def show
        @event = Event.find_by name: params[:event_name]
    end
    
    def edit
        @event = Event.find(params[:id])
        grab_officers
    end
    
    def update
        @event = Event.find(params[:id])
        
        # update the going/waitlist according to the new capacity if it was updated
        if(@event.capacity != params[:capacity])
            update_lists(@event.capacity, params[:capacity], @event.id)
        end
        
        # convert date input to correct format for database
        date = date_conversion
        @event.update_attributes!(:name => params[:name],
                 :description => params[:description],
                 :address => params[:address],
                 :meeting => params[:meeting],
                 :date => date,
                 :start_time => params[:start_time],
                 :end_time => params[:end_time],
                 :max_points => params[:max_points],
                 :capacity => params[:capacity],
                 :contact => params[:contact],
                 :publish => params[:publish],
                 :image => params[:image])

        flash[:success] = "#{@event.name} was successfully updated."

        redirect_to events_path
    end
    
    private
        def event_params
            params.require(:event).permit(:name, :description, :address, :meeting, :UIN, :date, :start_time, :end_time, :max_points, :contact, :image)
        end
        
        def contact_uin_to_email
            # make the contact attribute represent the EMAIL instead of UIN 
            @upcoming_events_email.each do |event|
                event_contact = User.find_by(UIN: event.contact)
                event.contact = event_contact.email   
            end
        end
        
        def date_conversion
            #convert date input of MM/DD/YYYY to YYYY-MM-DD
            if not params[:date].nil?
                date_arr = params[:date].split('/')
                date = date_arr[2] + '-' + date_arr[0] + '-' + date_arr[1]
            else
                date = "2001-01-01"
            end
            return date
        end
        
        def grab_officers
            @officers = User.where("officer = :officer", {officer: [true]})
        end
        
        def update_lists(old_capacity, new_capacity, event_id)
            
            if(old_capacity > new_capacity.to_i)
                # move ppl from going list to waitlist
                num_records = old_capacity - new_capacity.to_i
                # first just try changing the waitlisted attribute to true
                records_to_waitlist = Attendance.where(:event_id => event_id, :wait_listed => false).last(num_records)

                records_to_waitlist.each do |r|
                    r.update_attributes!(:wait_listed => true)
                end
                
            elsif(old_capacity < new_capacity.to_i)
                # move ppl from wait list to going list
                 num_records = new_capacity.to_i - old_capacity
                # first just try changing the waitlisted attribute to false
                records_to_waitlist = Attendance.where(:event_id => event_id, :wait_listed => true).first(num_records)
                records_to_waitlist.each do |r|
                    r.update_attributes!(:wait_listed => false)
                end
            end
        end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<!-- redirects members trying to "hack" into the admin pages -->
<%= member_redirect() %>

<h1 class="title">Edit Event</h1>
  <div class="edit-form">
      <div class="row">
        <div class="col-sm-6">
          <!--< form_tag :method => :put,  :controller => 'events', :action => 'update' do %>-->
          <%= form_tag event_path(@event), :method => :put do %>
            <div class="form-group row col-sm-12">
              <%= label_tag :name %>
            </div>
            <div class="form-group row col-sm-12">
              <input name="name" id="name_id" type="text" class="form-control" placeholder="Event Name" autofocus="" required value='<%= @event.name %>'>
            </div>
            
            <div class="form-group row col-sm-12">
              <%= label_tag :description %>
            </div>
            <div class="form-group row col-sm-12">
              <textarea class="form-control" name="description" id="description_id" rows="5"  placeholder="Description" required><%= @event.description %></textarea>
            </div>
            
            <div class="form-group row col-sm-12">
                <%= label_tag :address %>
            </div>
            <div class="form-group row col-sm-12">
              <textarea class="form-control" name="address" id="address_id" rows="3" placeholder="Address" required><%= @event.address %></textarea>
            </div>
            
            <div class="form-group row col-sm-12">
                <%= label_tag :meeting %>
            </div>
            <div class="form-group row col-sm-12">
                <div class="form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" type="radio" name="meeting" value=true >  Yes
                    </label>
                </div>
                <div class="form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" type="radio" name="meeting" value=false checked="checked">  No
                    </label>
                </div>
            </div>
            
            <div class="form-group row col-sm-12">
              <%= label_tag :date %>
            </div>
            <div class="form-group row col-sm-12">
              <div class='input-group date' id='datetimepicker1'>
                <input name="date" id="date_id" type="text" class="form-control" placeholder="" autofocus="" data-provide="datepicker" required value='<%= @event.date.strftime("%m/%d/%Y") %>'>
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
              </div>
            </div>
            
            <div class="form-group row col-sm-12">
              <%= label_tag :start_time %>
            </div>
            <div class="form-group row col-sm-12">
                <input name="start_time" id="start_time_id" class="form-control" type="time" value="<%= @event.start_time.strftime("%H:%M") %>" required>
            </div>
            
            <div class="form-group row col-sm-12">
              <%= label_tag :end_time %>
            </div>
            <div class="form-group row col-sm-12">
              <input name="end_time" id="end_time_id" class="form-control" type="time" value="<%= @event.start_time.strftime("%H:%M") %>" required>
            </div>
            
            <div class="form-group row col-sm-12">
              <%= label_tag :max_points %>
            </div>
            <div class="form-group row col-sm-12">
              <input name="max_points" id="max_points_id" class="form-control" type="number" value="<%= @event.max_points %>" required>
            </div>
            
            <div class="form-group row col-sm-12">
              <%= label_tag :volunteer_capacity %>
            </div>
            <div class="form-group row col-sm-12">
              <input name="capacity" id="capacity_id" class="form-control" type="number" value="<%= @event.capacity %>" required>
            </div>
            
            <div class="form-group row col-sm-12">
              <%= label_tag :contact %>
            </div>
            <div class="form-group row col-sm-12">
              <select class="btn-group bootstrap-select show-tick" name="contact" required>
                <!-- list the officers -->
                <% @officers.each do |officer| %>
                  <!-- must convert UIN to string because that is how we store it in Event Model -->
                  <% if officer.UIN.to_s == @event.contact %>
                      <option selected value=<%= officer.UIN %> selected> <%= officer.name %> </option>
                  <% else %>
                      <option value=<%= officer.UIN %>> <%= officer.name %> </option>
                  <% end %>
                <% end %>
              </select>
            </div>
            
            <div class="form-group row col-sm-12">
              <%= label_tag :publish %>
          </div>
          <div class="form-group row col-sm-12">
                <% if @event.publish %>
                  <div class="form-check">
                    <label class="form-check-label">
                      <input class="form-check-input" type="radio" name="publish" value=true required checked="checked">  Yes
                    </label>
                  </div>
                  <div class="form-check">
                    <label class="form-check-label">
                      <input class="form-check-input" type="radio" name="publish" value=false >  No
                    </label>
                  </div>
                <% else %>
                  <div class="form-check">
                    <label class="form-check-label">
                      <input class="form-check-input" type="radio" name="publish" value=true required>  Yes
                    </label>
                  </div>
                  <div class="form-check">
                    <label class="form-check-label">
                      <input class="form-check-input" type="radio" name="publish" value=false checked="checked">  No
                    </label>
                  </div>
                <% end %>
          </div>
            
            <div class="form-group row col-sm-12">
              <%= label_tag :image %>
            </div>
            <div class="form-group row col-sm-12">
              <input name="image" id="image_id" class="form-control" value="<%= @event.image %>" >
            </div>
            
            <div class="form-group row col-sm-12">
              <div class="offset-sm-7 col-sm-2">
                <a href="<%= events_path %>" id="cancel_create_btn" class="btn btn-default">Cancel</a>
              </div>
              <div class="col-sm-2">
                <%= submit_tag "Submit", :class => "btn btn-success"%>
              </div>
            </div>
            
          <% end %>
        </div> <!-- end col-sm-6 -->
        
        <div class="col-sm-6">
          <div class="form-group row col-sm-12">
            <%= form_tag '/img_upload/create', { :multipart => true} do %>  
              <p>
                <%= file_field_tag 'upload[file]'  %>
              </p>
              <p>
                  <!--%= submit_tag "Upload", :class => "btn btn-default", :onclick => "update_img()"%>-->
                  <%= submit_tag "Upload", :class => "btn btn-default" %>
              </p>
            <% end %>
          </div>
          <div class="row col-sm-12 event-image">
              <%= image_tag(@event.image, class: "img-thumbnail") %>
              <!--<img src="" id="image_tag_id" class="img-thumbnail">-->
          </div>
        </div> <!-- end of col-sm-6 -->
        
      </div>
  </div>
  
        <script>
  function grab_img_file(){
    return document.getElementById("upload_file").files[0].name;
  }
  document.getElementById("upload_file").onchange = function(){
    document.getElementById('image_id').value = grab_img_file();
  }
  function update_img(){
    var img_file = grab_img_file();
    var src = "/assets/" + img_file;
    document.getElementById("image_tag_id").src = src;
  }
  // $("#upload_file").on('submit', function(e) {
  //   e.preventDefault();
  //   $.ajax({
  //       type: $(this).prop('method'),
  //       url : $(this).prop('action'),
  //       data: $(this).serialize()
  //   }).done(function() {
  //       update_img();
  //   });
  // });
</script>

app/views/events/index.html.erb
<%= javascript_include_tag "events" %>
<h1 class="title">Upcoming Events</h1>
<%= render 'layouts/flash_messages' %>
<br>
<% @upcoming_events_email.each do |event| %>
    <div class="event-card">
        <div class="row">
            <div class="col-sm-9">
                <div class="row col-sm-12">
                    <h3 id="event_title"><%= event.name %></h3>
                </div>
                <div class="row col-sm-12">
                    <b>Time: </b>
                    <div class="event-item-margin">
                        <%= event.start_time.strftime("%I:%M %p")%>
                        -
                        <%= event.end_time.strftime("%I:%M %p") %>
                    </div>
                </div>
                <div class="row col-sm-12">
                    <b>Date: </b>
                    <div class="event-item-margin">
                        <%= event.date.strftime("%B %d, %Y") %>
                    </div>
                </div>
                <div class="row col-sm-12">
                    <b>Contact: </b>
                    <div class="event-item-margin">
                        <%= event.contact %>
                    </div>
                </div>
                <b>Description: </b>
                <div class="row col-sm-12">
                    <%= event.description %>
                </div>
            </div>
            
            <div class="col-sm-3">
                <div class="row col-sm-12">
                    Points: 
                    <%= event.max_points %>
                </div>
                <div class="row col-sm-12">
                    Spots Remaining: <%= event.capacity-(Attendance.where(event_id: event.id, wait_listed: false).count)%>
                    <!--<%= event.capacity %>-->
                </div>
                <div class="row col-sm-12 event-image">
                    <!-- images are stored on cloudinary -->
                    <%= cl_image_tag(event.image, class: "img-thumbnail") %>
                </div>
                <div class="row col-sm-12">
                    <a href="" id="address" class="address" target="_blank"><%= event.address %></a>
                </div>
                <div class="row col-sm-12">
                     <!--if admin -->
                    <% if session[:admin] %>
                        <div class="row col-sm-12">
                            <div class="col-xs-6 event-btn">
                                <a href=<%= edit_event_path(event) %> class="btn btn-default btn-block">Edit</a>
                            </div>
                            <div class="col-xs-6 event-btn">
                                <%= button_to "Delete", event_path(event,:event_name => event.name), method: :delete, class: "btn btn-danger btn-block", data: { confirm: 'Are you sure you want to delete ' + event.name.to_s + '?' }  %>
                            </div>
                        </div>
                        <div class="row col-xs-12 event-btn">
                            <a href=<%= attendances_event_attendees_path(:event_id => event.id ) %>  class="btn btn-default btn-block">View Sign Ups</a>
                        </div>
                    
                    <!-- general user -->    
                    <% elsif Attendance.where(:UIN => session[:user_uin]).where(:event_id => event.id).present? %>
                     <!--Check to see if member is signed up. Show 'signup' button if not signed up and 'remove me' button otherwise-->
                        <div class="col-sm-12 event-btn">
                            <%= button_to "Remove Me", { :action => "remove_from_event", :event_id => event.id },
                            {class: 'btn btn-danger btn-block'} %>
                        </div>

                    <% else %>
                        <div class="col-sm-12 event-btn">
                            <%= button_to "Sign Up", { :action => "sign_up_for_event", :event_id => event.id }, {class: 'btn btn-success btn-block'} %>
                        </div>
                    <% end %>
                    <!-- end --> 
                </div>
            </div>
        </div>
    </div>
    <br>
<% end %>

<script>
// couldnt get the script to run from any of the coffee files 
$(document).ready(function(){
    var $editItem, $elements, $link, $pluslink, i;
    $elements = document.getElementsByClassName('address');
    i = 0;
    while (i < $elements.length) {
        $editItem = $elements[i];
        $link = $editItem.text;
        $pluslink = $link.replace(/\s+/g, '+');
        $elements[i].href = 'https://www.google.com/maps?q=' + $pluslink;
        $elements[i].text = 'Google Maps Link';
        i++;
    }
});
</script>

app/views/events/new.html.erb
<%= cloudinary_js_config %>

<!-- redirects members trying to "hack" into the admin pages -->
<%= member_redirect() %>

<h1 class="title">Create Event</h1>
  <div class="create-form">
    <%= form_for :event, url: events_path do |f| %>
      <div class="row">
        <div class="col-sm-6">
          
          
          
          <div class="form-group row col-sm-12">
            <%= f.label :name %>
          </div>
          <div class="form-group row col-sm-12">
            <input name="name" id="name_id" type="text" class="form-control" placeholder="Event Name" autofocus="" required>
          </div>
          
          
          
          
          <div class="form-group row col-sm-12">
            <%= f.label :description %>
          </div>
          <div class="form-group row col-sm-12">
            <textarea class="form-control" name="description" id="description_id" rows="5"  placeholder="Description" required></textarea>
          </div>
          
          
          
          
          <div class="form-group row col-sm-12">
              <%= f.label :address %>
          </div>
          <div class="form-group row col-sm-12">
            <textarea class="form-control" name="address" id="address_id" rows="3" placeholder="Address" required></textarea>
          </div>
          
          
          
          
            <div class="form-group row col-sm-12">
              <%= f.label :meeting %>
            </div>
            <div class="form-group row col-sm-12">
              <div class="form-check">
                <label class="form-check-label">
                  <input class="form-check-input" type="radio" name="meeting" value=true required>  Yes
                </label>
              </div>
              <div class="form-check">
                <label class="form-check-label">
                  <input class="form-check-input" type="radio" name="meeting" value=false >  No
                </label>
              </div>
            </div>
          
          
          
          
          
          <div class="form-group row col-sm-12">
            <%= f.label :date %>
          </div>
          <div class="form-group row col-sm-12">
            <div class='input-group date' id='datetimepicker1'>
              <input name="date" id="date_id" type="text" class="form-control" placeholder="" autofocus="" data-provide="datepicker" required>
              <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
              </span>
            </div>
          </div>
          
          
          
          
          
          <div class="form-group row col-sm-12">
            <%= f.label :start_time %>
          </div>
          <div class="form-group row col-sm-12">
              <input name="start_time" id="start_time_id" class="form-control" type="time" value="13:45:00" required>
          </div>
          
          
          
          
          <div class="form-group row col-sm-12">
            <%= f.label :end_time %>
          </div>
          <div class="form-group row col-sm-12">
            <input name="end_time" id="end_time_id" class="form-control" type="time" value="14:45:00" required>
          </div>
          
          
          
          <div class="form-group row col-sm-12">
            <%= f.label :max_points %>
          </div>
          <div class="form-group row col-sm-12">
            <input name="max_points" id="max_points_id" class="form-control" type="number" value="0.0" required>
          </div>
          
          <div class="form-group row col-sm-12">
            <%= f.label :volunteer_capacity %>
          </div>
          <div class="form-group row col-sm-12">
            <input name="capacity" id="capacity_id" class="form-control" type="number" value="0" required>
          </div>
          
          
          <div class="form-group row col-sm-12">
            <%= f.label :contact %>
          </div>
          <div class="form-group row col-sm-12">
            <!--<input name="contact" id="contact_id" class="form-control" value="" pattern="[0-9]{9}" required>-->
            <select class="btn-group bootstrap-select show-tick" name="contact" required>
                  <option disabled selected value> -- Select Officer -- </option>
                  <!-- list the officers -->
                  <% @officers.each do |officer| %>
                    <option value=<%= officer.UIN %>> <%= officer.name %> </option>
                  <% end %>
                </select>
          </div>
          
          <div class="form-group row col-sm-12">
              <%= f.label :publish %>
          </div>
          <div class="form-group row col-sm-12">
            <div class="form-check">
              <label class="form-check-label">
                <input class="form-check-input" type="radio" name="publish" value=true required>  Yes
              </label>
            </div>
            <div class="form-check">
              <label class="form-check-label">
                <input class="form-check-input" type="radio" name="publish" value=false >  No
              </label>
            </div>
          </div>
          
          
          
          <div class="form-group row col-sm-12">
            <%= f.label :image %>
          </div>
          <div class="form-group row col-sm-12">
            <input name="image" id="image_id" class="form-control" value="" >
          </div>
          
          
          
          
          <div class="form-group row col-sm-12">
            <div class="offset-sm-7 col-sm-2">
              <a href=<%= dashboard_index_path %> id="cancel_create_btn" class="btn btn-default">Cancel</a>
            </div>
            <div class="col-sm-2">
              <%= f.submit :class => "btn btn-success"%>
            </div>
          </div>
          
          
        </div>
        <% end %>
        <div class="col-sm-6">
          <div class="form-group row col-sm-12">
            <%= form_tag '/img_upload/create', { :multipart => true} do %>  
              <p>
                <%= file_field_tag 'upload[file]'  %>
              </p>
              <p>
                  <%= submit_tag "Upload", :class => "btn btn-default", :onclick => "update_img()"%>
                  <!--%= submit_tag "Upload", :class => "btn btn-default" %>-->
              </p>
            <% end %>
          </div>
          <!--<div class="row col-sm-12 event-image">-->
          <!--    %= image_tag(@img_file, class: "img-thumbnail") %>-->
          <!--    <img src="" id="image_tag_id" class="img-thumbnail">-->
          <!--</div>-->
           
          
        </div>
      </div>
    
    
      
  </div>
  
<script>
  function grab_img_file(){
    return document.getElementById("upload_file").files[0].name;
  }
  document.getElementById("upload_file").onchange = function(){
    document.getElementById('image_id').value = grab_img_file();
  }
  function update_img(){
    var img_file = grab_img_file();
    var src = "/assets/" + img_file;
    document.getElementById("image_tag_id").src = src;
  }
  // $("#upload_file").on('submit', function(e) {
  //   e.preventDefault();
  //   $.ajax({
  //       type: $(this).prop('method'),
  //       url : $(this).prop('action'),
  //       data: $(this).serialize()
  //   }).done(function() {
  //       update_img();
  //   });
  // });
  
  $(function() {
    if($.fn.cloudinary_fileupload !== undefined) {
      $("input.cloudinary-fileupload[type=file]").cloudinary_fileupload();
    }
  });
</script>