config/routes.rb
Rails.application.routes.draw do

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    post 'user/login'
    get 'user/new'
    post 'user/logout'
    get 'user/admin_login'
    post 'user/admin_password_validation'
    
    post 'events/new'
    get 'events/sign_up_for_event'
    post 'events/sign_up_for_event'
    post 'events/remove_from_event'
    
    get 'attendances/event_attendees'
    post 'attendances/event_attendees'
    post 'attendances/remove_from_event'
    
    get 'points/meeting'
    post 'points/meeting_signin'
    # get 'points/view_approve_event'
    # post 'points/select_approve_event'
    get 'points/select_approve_points'
    post 'points/view_users_approval'
    get 'points/view_users_approval'
    post '/points/approve_points'
    get 'points/user_list'
    get 'points/member_activity_table'
    post 'points/update'
    get 'points/user_csv'
    
    #   get 'events/new'
    
    get 'dashboard/index'
    post 'dashboard/index'
    
    get 'attendances/view_details'
    post 'attendances/view_details'
    
    post 'img_upload/create'
    
    post 'admin/update'
    get 'admin/export_data'
    
    resources :events
    resources :user
    resources :points
    resources :attendances
    resources :admin
    
    root 'user#login'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/user.rb
require 'csv'
class User < ApplicationRecord
    def self.to_csv
        CSV.generate(headers: true) do |csv|
            csv << %w{ name phone email address classification major shirt gender officer active points} 
            all.each do |user|
                points = Point.where(UIN: user.UIN).sum(:points)
                csv << [ user.name, user.phone, user.email, user.address, user.classification, user.major, user.shirt, user.gender, user.officer, user.active, points]
            end
        end
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	before_filter :authenticate_user!, :only => [ :index, :update ]
	layout "application", :only => [ :index, :new, :edit ]
	layout "login", :only => [:login, :admin_login]

	#displays all the users that can be editted
	def index
		@users = User.order(:name).all
		
		respond_to do |format|
    		format.html
    		format.csv { send_data @users.to_csv, filename: "users-#{Date.today}.csv" }
    	end
	end
	
	def login
		# render layout: "login"
		# check if admin or member is trying to login
		if params[:login_UIN] == "admin"
			# ask for password
			redirect_to user_admin_login_path
		elsif !params[:login_UIN].nil?
			# member login
			user_uin = params[:login_UIN]
			if User.exists?({:UIN => user_uin}) #and !user_uin.nil?
				
				# if uin is correct assign this session variable for use in other areas in application
				session[:user_uin] = user_uin
				# to correctly display certain buttons
				session[:admin] = false
				
				# successful login redirect to dashbaord path
				redirect_to dashboard_index_path
			else
				# uin does not exist in database
				flash[:warning] = "Invalid UIN. Do you need to Sign Up?"
				redirect_to root_path(:login_error => "invalid_user")
			end
		end
		
	end

	def admin_password_validation
		hashed_password = Digest::SHA2.hexdigest(params[:admin_password])
		pass = Admin.find(1).password
		if pass == hashed_password
			# redirect_to root_path(:login_error => "invalid_password")
			session[:admin] = true
			redirect_to dashboard_index_path
		else
			flash[:danger] = "Incorrect Admin password."
			redirect_to root_path
		end
	end
	
	def new
		# creates the correct "Go Back" link for user creation since we use the form in 2 different locations: Login, Meeting Sign In
		session[:new_user_back] = URI(request.referer || '').path
		if session[:new_user_back] == "/"
			render layout: "login"
		end
	end
	
	def create
		address = params[:street] + ' ' + params[:city] + ', ' + params[:state] + ' ' + params[:zip]
		@new_user = User.create!(:name => params[:name],
                 :UIN => params[:UIN],
                 :phone => params[:phone],
                 :email => params[:email],
                 :address => address,
                 :classification => params[:classification],
                 :major => params[:major],
                 :shirt => params[:shirt],
                 :gender => params[:gender],
                 :officer => false,
                 :active => false)
                 
        @new_user.save
		flash[:success] = "Created User: " + @new_user.name
		
		#redirect_to root_path
		redirect_to session[:new_user_back]
	end

	def logout
		# action that is called when logout button is clicked
		# should be clearing necessary information like this, not sure if we need anything else for now this is enough
		session[:user_uin] = nil
		session[:admin] = nil
		flash[:success] = "Successfully logged out."
		redirect_to root_path
	end
	
	def edit
		@user = User.find params[:id]
		@shirt_sizes = ["X-Small","Small","Medium", "Large", "X-Large", "XX-Large", "XXX-Large"]
		@classifications = ["Freshman","Sophomore","Junior","Senior","Graduate"]
	end
	
	def update
        @user = User.find(params[:id])
        # convert date input to correct format for database
       
        @user.update_attributes!(:name => params[:name],
                 :phone => params[:phone],
                 :email => params[:email],
                 :address => params[:address],
                 :classification => params[:classification],
                 :major => params[:major],
                 :shirt => params[:shirt],
                 :gender => params[:gender],
                 :officer => params[:officer],
                 :active => params[:active],
                 :updated_at => DateTime.now)

        flash[:success] = "#{@user.name} was successfully updated."
        redirect_to user_index_path
	end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/admin_login.html.erb
<!-- redirects members trying to "hack" into the admin pages -->
<%= member_redirect() %>

<%= form_tag :method => :post, :class => 'form-signin', :controller => 'user', :action => 'admin_password_validation' do %>
   <html>
    <!-- <head/> -->
    <style>
        .center {
          margin: auto;
          width: 30%;
          padding: 10px;
        }
    </style>
  </html>

  <h1 class="form-signin-heading text-muted center">Admin Log In</h1>

  <div class="center">
 	<input name="admin_password" id="admin_password_id" type="password" class="form-control" placeholder="Admin Password" required="" autofocus="">
 </div>
  <div class="row">
    <div class="center">
      <button name="admin_login_button" id="admin_login_id" class="btn btn-lg btn-primary btn-block" type="submit">Log In</button>
    </div>
  </div>
<% end %>

app/views/user/edit.html.erb
<style style="text/css">
  .caret {
    border-color: transparent !important;
  }
</style>

<!-- redirects members trying to "hack" into the admin pages -->
<%= member_redirect() %>

<h1 class="title">Edit User</h1>
  <div class="create-form">
    <%= form_for :user, url: user_path do |f| %>
      <div class="row">
        <div class="col-sm-6">
          <%= form_tag user_index_path, :method => :put do %>
          
          <div class="form-group row col-sm-12">
            <%= f.label :name %>
          </div>
          <div class="form-group row col-sm-12">
                  <%= f.text_field :name, :value => @user.name, name: "name", class: "form-control", id:"name_id", type:"text", :required=>true %>
          </div>
          
          <div class="form-group row col-sm-12">
            <%= f.label :phone %>
          </div>
          <div class="form-group row col-sm-12">
                  <%= f.text_field :phone, :value => @user.phone, name: "phone", class: "form-control", id:"phone_id", type:"text", :required=>true %>
          </div>
          
          
          <div class="form-group row col-sm-12">
            <%= f.label :email %>
          </div>
          <div class="form-group row col-sm-12">
                  <%= f.text_field :email, :value => @user.email, name: "email", class: "form-control", id:"email_id", type:"text", :required=>true %>
          </div>
          
          <div class="form-group row col-sm-12">
            <%= f.label :address %>
          </div>
          <div class="form-group row col-sm-12">
                  <%= f.text_field :address, :value => @user.address, name: "address", class: "form-control", id:"address_id", type:"text", :required=>true %>
          </div>
          
          <div class="form-group row col-sm-12">
            <%= f.label :classification %>
          </div>
          <div class="form-group row col-sm-12">
            <select class="btn-group bootstrap-select show-tick" name="shirt" required>
                  <% @classifications.each do |classification| %>
                    <% if classification == @user.classification %>
                      <option value=<%= classification %> selected><%= classification %> </option>
                    <% else %>
                      <option value=<%= classification %>><%= classification %> </option>
                    <% end %>
                  <% end %>
                </select>
          </div>
          
          <div class="form-group row col-sm-12">
            <%= f.label :major %>
          </div>
          <div class="form-group row col-sm-12">
                  <%= f.text_field :major, :value => @user.major, name: "major", class: "form-control", id:"major_id", type:"text", :required=>true %>
          </div>
          
          <div class="form-group row col-sm-12">
            <%= f.label :shirt %>
          </div>
          <div class="form-group row col-sm-12">
            <select class="btn-group bootstrap-select show-tick" name="shirt" required>
                  <% @shirt_sizes.each do |size| %>
                    <% if size == @user.shirt %>
                      <option value=<%= size %> selected><%= size %> </option>
                    <% else %>
                      <option value=<%= size %>><%= size %> </option>
                    <% end %>
                  <% end %>
                </select>
          </div>
          
          
          <div class="form-group row col-sm-12">
              <%= f.label :gender %>
          </div>
          <div class="form-group row col-sm-12">
            <div class="form-check">
              <label class="form-check-label">
                <% if @user.gender == "male" %>
                  <%= radio_button_tag(:gender, "male",checked="true") %> <%= :Male %>
                <% else %>
                  <%= radio_button_tag(:gender, "male") %> <%= :Male %>
                <% end %>
              </label>
            </div>
            <div class="form-check">
              <label class="form-check-label">
                <% if @user.gender == "female" %>
                  <%= radio_button_tag(:gender, "female", checked="true") %> <%= :Female %>
                <% else %>
                  <%= radio_button_tag(:gender, "female") %> <%= :Female %>
                <% end %>
              </label>
            </div>
          </div>
          
          <div class="form-group row col-sm-12">
              <%= f.label :officer %>
          </div>
          <div class="form-group row col-sm-12">
            <div class="form-check">
              <label class="form-check-label">
                <% if @user.officer %>
                  <%= radio_button_tag(:officer, "true",checked="true") %> <%= :Yes %>
                <% else %>
                  <%= radio_button_tag(:officer, "true") %> <%= :Yes %>
                <% end %>
              </label>
            </div>
            <div class="form-check">
              <label class="form-check-label">
                <% if @user.officer %>
                  <%= radio_button_tag(:officer, "false") %> <%= :No %>
                <% else %>
                  <%= radio_button_tag(:officer, "false", checked="true") %> <%= :No %>
                <% end %>
              </label>
            </div>
          </div>
          
          <div class="form-group row col-sm-12">
              <%= f.label :active %>
          </div>
          <div class="form-group row col-sm-12">
            <div class="form-check">
              <label class="form-check-label">
                <% if @user.active %>
                  <%= radio_button_tag(:active, "true",checked="true") %> <%= :Yes %>
                <% else %>
                  <%= radio_button_tag(:active, "true") %> <%= :Yes %>
                <% end %>
              </label>
            </div>
            <div class="form-check">
              <label class="form-check-label">
                <% if @user.active %>
                  <%= radio_button_tag(:active, "false") %> <%= :No %>
                <% else %>
                  <%= radio_button_tag(:active, "false", checked="true") %> <%= :No %>
                <% end %>
              </label>
            </div>
          </div>
          
          <div class="form-group row col-sm-12">
            <div class="offset-sm-7 col-sm-2">
              <a href="<%= user_index_path %>" id="cancel_create_btn" class="btn btn-default">Cancel</a>
            </div>
            <div class="col-sm-2">
              <%= submit_tag "Submit", :class => "btn btn-success"%>
            </div>
          </div>
          
          
          
  
          
          
        <% end %>  
        </div>
      </div>
      <% end%>
  </div>

app/views/user/index.html.erb
<style style="text/css">
.table-hover tbody tr:hover td, .table-hover tbody tr:hover th {
  background-color: #dedede;
}
</style>

<!-- redirects members trying to "hack" into the admin pages -->
<%= member_redirect() %>

<div class="container">

  <h2>Select User</h2>
  <h4><span class="label label-primary">Please select a user to edit</span></h4>
  <%= render 'layouts/flash_messages' %>

  
  <div class="page-margins">
    <div class="table-responsive">
      <table class="table table-striped table-hover table-fixed">
        <thead>
          <tr>
            <th class="col-sm-1">Name</th>
            <th class="col-sm-1">UIN</th>
            <th class="col-sm-1">Officer</th>
            <th class="col-sm-1">Active</th>
            <th class="col-sm-1">Email</th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr data-link="<%= edit_user_path(user) %>">
              <td><%= user.name %></td>
              <td><%= user.UIN %></td>
              <td>
                <% if user.officer %>
                  <span class="glyphicon glyphicon-ok" style="color: green;"></span>
                <% end %>
              </td>
              <td>
                <% if user.active %>
                  <span class="glyphicon glyphicon-ok" style="color: green;"></span>
                <% end %>
              </td>
              <td><%= user.email %></td>
              <!--<td><= user.UIN %></td>-->
              <!--<td><= user.name %></td>-->
              <!--<td>x</td>-->
              <!--<td>Input Stuff here</td>-->
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  
  <% if flash[:success] %>
    <div class="alert <= "alert-success" %> fade in">
      <button class="close" data-dismiss="alert">×</button>
      Update Success
    </div>
  <% end %>
</div>

<script>
    $("tr[data-link]").click(function() {
  window.location = $(this).data("link")
})
</script>

<script>
  setTimeout("$('.alert').fadeOut('slow')", 1000)
</script>

app/views/user/list.html.erb
<style style="text/css">
.table-hover tbody tr:hover td, .table-hover tbody tr:hover th {
  background-color: #dedede;
}
</style>

<!-- redirects members trying to "hack" into the admin pages -->
<%= member_redirect() %>

<div class="container">

  <h2>Select User</h2>
  <h4><span class="label label-primary">Please select a user to edit</span></h4>
  <%= render 'layouts/flash_messages' %>

  
  <div class="page-margins">
    <div class="table-responsive">
      <table class="table table-striped table-hover table-fixed">
        <thead>
          <tr>
            <th class="col-sm-1">Name</th>
            <th class="col-sm-1">UIN</th>
            <th class="col-sm-1">Officer</th>
            <th class="col-sm-1">Active</th>
            <th class="col-sm-1">Email</th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr data-link="<%= edit_user_path(user) %>">
              <td><%= user.name %></td>
              <td><%= user.UIN %></td>
              <td>
                <% if user.officer %>
                  <span class="glyphicon glyphicon-ok" style="color: green;"></span>
                <% end %>
              </td>
              <td>
                <% if user.active %>
                  <span class="glyphicon glyphicon-ok" style="color: green;"></span>
                <% end %>
              </td>
              <td><%= user.email %></td>
              <!--<td><= user.UIN %></td>-->
              <!--<td><= user.name %></td>-->
              <!--<td>x</td>-->
              <!--<td>Input Stuff here</td>-->
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  
  <% if flash[:success] %>
    <div class="alert <= "alert-success" %> fade in">
      <button class="close" data-dismiss="alert">×</button>
      Update Success
    </div>
  <% end %>
</div>

<script>
    $("tr[data-link]").click(function() {
  window.location = $(this).data("link")
})
</script>

<script>
  setTimeout("$('.alert').fadeOut('slow')", 1000)
</script>

app/views/user/login.html.erb
<%= form_tag :method => :post, :class => 'form-signin', :controller => 'user', :action => 'login' do %>
  <h1 class="form-signin-heading text-muted center" style="color:white !important;">Log In/Sign Up</h1>

  <%= render 'layouts/flash_messages' %>

  <html>
    <style>
        .center {
          margin: auto;
          width: 40%;
          padding: 10px;
        }
        body {
          background-image: url("http://res.cloudinary.com/aggie-rotaract/image/upload/v1491769469/Aggie-Rotaract-Homepage.jpg");
          background-size: cover !important;
        }
    </style>
  </html>
  <body>
    <div class="center">
      <input name="login_UIN" id="login_UIN_id" type="text" class="form-control" maxlength="9" placeholder="UIN" required="" autofocus="">
      
      <div class="login-btn-padding">
        <div class="col-md-6">
          <button name="login_button" id="login_button_id" class="btn btn-lg btn-primary btn-block" type="submit">Log In</button>
        </div>
        <div class="col-md-6">
          <a href=<%= new_user_path %> id="sign_up_button_id" class="btn btn-lg btn-default btn-block">Sign Up</a>
        </div>
      </div>
    </div>
  </body></body>
<% end %>

<!--%= cl_image_tag("Aggie-Rotaract-Homepage.jpeg")%>-->

<style>
  
</style>

<!--%= cl_image_tag("sample.jpg", :alt => "Sample Image", -->
<!--  :width => 100, :height => 150) %> -->
<!--%= image_tag(-->
<!--  "http://res.cloudinary.com/aggie-rotaract/image/upload/v1490643285/sample.jpg", -->
<!--  :width => 100, :height => 150) %>-->

app/views/user/new.html.erb
<html>
    <!-- <head/> -->
    <style>
        .center {
          margin: auto;
          width: 30%;
          /*padding: 10px;*/
        }

        label { padding-bottom: 10px;
          font-weight: normal;
        }
    </style>
</html>

<%= form_tag :method => :post, :class => 'form-signin', :controller => 'user', :action => 'create' do %>

  <div class="center">
    <h1>Create New User</h1>
    <label>
  	 <input name="UIN" type="text" class="form-control" pattern="\d{9}" maxlength="9" placeholder="UIN" autofocus="" required>
    </label>

    <label>
      <input name="name" type="text" class="form-control" pattern="[a-zA-Z ]+" placeholder="Name" autofocus="" required>
    </label>

    <label>
      <input name="phone" type="text" class="form-control" pattern="\d{10}" maxlength="10" placeholder="Phone" autofocus="" required>
    </label>
  	
    <label>
      <input name="email" type="text" class="form-control" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$" placeholder="Email" autofocus="" required>
    </label>

    <label>
      <input name="street" type="text" class="form-control" placeholder="Street" autofocus="" required>
    </label>

    <label>
      <input name="city" type="text" class="form-control" placeholder="City" autofocus="" required>
    </label>

    <label>
      <input name="state" type="text" class="form-control" placeholder="State" autofocus="" required>
    </label>
  	
    <label>
      <input name="zip" type="text" class="form-control" placeholder="ZIP Code" autofocus="" required>
    </label>
  	
    <label>
      Classification:
      <select name="classification" required>
        <option value="Freshman">Freshman</option>
        <option value="Sophomore">Sophomore</option>
        <option value="Junior">Junior</option>
        <option value="Senior">Senior</option>
        <option value="Graduate">Graduate</option>
      </select>
    </label>
  	
    <label>
      <input name="major" type="text" class="form-control" maxlength="9" placeholder="Major" autofocus="" required>
    </label>
  	
    <label>
      Shirt Size:
      <select name="shirt" required>
        <option value="X-Small">X-Small</option>
        <option value="Small">Small</option>
        <option value="Medium">Medium</option>
        <option value="Large">Large</option>
        <option value="X-Large">X-Large</option>
        <option value="XX-Large">XX-Large</option>
        <option value="XXX-Large">XXX-Large</option>
      </select>
    </label>

    <label>
      Gender:
      <form action="" name="gender" required>
        <input type="radio" name="gender" value="male"> Male
        <input type="radio" name="gender" value="female"> Female
      </form>
    </label>

  	<div class="col-md-8">
      <button class="btn btn-lg btn-primary btn-block" type="submit">Create User</button>
    </div>
    <div class="col-md-8" style="padding-top: 1em;">
      <a href=<%= session[:new_user_back] %> class="btn btn-lg btn-default btn-block" >Go Back</a>
    </div>
  </div>
<% end %>
    